name: hello-world
on: push
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!!"
  my-second-job:
    runs-on: ubuntu-latest
    needs: my-first-job
    steps:
      - name: my-step
        run: echo "BYEBYE"
